### ISSUE TITLE
[Question] Is it compatible with other extensions like adblock? 

### ISSUE THREAD

**Issue by rpgdev** [szymonszewcjr/LegacyTweaks#1]
Is it compatible with other extensions like adblock? Asking before I go through the trouble of installing since it requires some fuzzing around :)

**Comment by szymonszewcjr** [comment]
Yes it is.

**Comment by rpgdev** [comment]
@szymonszewcjr thanks. I could do with previous redesigns but the last one that doesn't offer a visual way to see the songs you've liked is **malicious** considering the very few if any organizing options that Spotify offers. I'll try this over the weekend.

**Comment by szymonszewcjr** [comment]
No worries, just make sure to use it with compatible spotify version, links provided in readme
