### ISSUE TITLE
Show "LegacyLook.js may not be compatible with this version of Spotify ..." dialog only once

### ISSUE THREAD

**Issue by rpgdev** [szymonszewcjr/LegacyTweaks#2]
Unfortunately on flathub (Linux) we don't have Spotify "1.2.10.760" available in the flathub repo but 1.2.9.743 which is right before that one. The extension seems to be working just fine with that version except for the warning below that keeps being shown every time I open spotify. I commented it out of the script but it'd be good if it was only shown once or twice and then it was gone forever.

```
LegacyLook.js may not be compatible with this version of Spotify.  This extension is compatible with Spotify 1.2.10.760. You are using ${Spicetify.Platform.PlatformData.event_sender_context_information.client_version_string}. If extension doesn't work, you may need to install Spotify 1.2.10.760. If it works on any other version, let me know, and I will add it to the compatibility list. You can disable this message in settings.
```

**Comment by szymonszewcjr** [comment]
Message itself already includes info on how to disable it.
Open spotify settings and under legacytweaks section you should have an option to disable the warning.

If it does appear there, it means that spicetify settings plugin is failing for some reason. In that case I would need logs to make sense of that.

**Comment by rpgdev** [comment]
>Message itself already includes info on how to disable it.

Besides updating spotify? Where? @szymonszewcjr 

> Open spotify settings and under legacytweaks section you should have an option to disable the warning.
![image](https://github.com/szymonszewcjr/LegacyTweaks/assets/20094474/37e1ae18-7367-4435-a896-838adc9bc3b8)
![image](https://github.com/szymonszewcjr/LegacyTweaks/assets/20094474/de3139ca-9f4f-4304-ae52-51f833dd9e35)

What's the name of the option?

**Comment by szymonszewcjr** [comment]
![image](https://github.com/szymonszewcjr/LegacyTweaks/assets/25388114/ae499ca4-2df1-4e44-a99a-58209f227da7)
Right there, if it doesn't show up on your side then spicetify setting extension messed something up.

**Comment by szymonszewcjr** [comment]
I just took a peek into the code, and it seems that this toggle only shows up if version is 1.2.10.760 exactly, dunno why I did that.
Welp that's a bug, my bad.
Will fix sometime next week.

**Comment by szymonszewcjr** [comment]
Fixed, please check out new version
