### ISSUE TITLE
Text not lining up on dropdown menus

### ISSUE THREAD

**Issue by DGee3** [szymonszewcjr/LegacyTweaks#3]
Text doesn't line up with the button on dropdown menus. I checked for other conflicts but it happens even without anything installed.
![Spotify-15꞉13꞉35_15 03 2024](https://github.com/szymonszewcjr/LegacyTweaks/assets/58882968/3c9594c6-8f69-445e-bba9-b1cced413cb9)

Fixed by changing
.main-type-mesto {
    margin-bottom: -60px;

to

.main-type-mesto {
    margin-bottom: 0px;

**Comment by szymonszewcjr** [comment]
There is a reason for this `margin-bottom: -60px;`. Due to setting plugin text on toggles did not line up, this was a temporary fix.

**Comment by szymonszewcjr** [comment]
Fixed, please see new version in dist.
