### ISSUE TITLE
Timed/karaoke lyrics are not autoscrolling

### ISSUE THREAD

**Issue by rpgdev** [szymonszewcjr/LegacyTweaks#4]
Timed/karaoke lyrics  are not autoscrolling, is that ok? The lines get highlighted alright but I need to manually scroll them, with stock spotify the current line is always centered.

**Comment by szymonszewcjr** [comment]
Same for me, but it did not bother me enough to fix it. 
All that needs to be done is to query for active lyrics line and scroll it into view. 
Something like this on an Interval would suffice:  `document.querySelector(".active_line_class").scrollIntoView()`

I may implement that fix later as a switchable toggle.

**Comment by rpgdev** [comment]
Is there a fix released somewhere at least as a gist? If not then the issue should be kept open until it gets fixed in some form..

**Comment by szymonszewcjr** [comment]
working on it rn, will upload in about 2hrs

**Comment by rpgdev** [comment]
Thanks @szymonszewcjr looking forward to it.

**Comment by szymonszewcjr** [comment]
Fixed, new dist available for download. Please do a factory reset of the extension settings after updating, there's a button for that now in spotify settings.
